### ISSUE TITLE
questions about "find.adapter " results

### ISSUE THREAD

**Issue by seven1112233** [ZhaiLab-SUSTech/FLEPSeq#3]
hi,
After finding adapter results, I find that some reads in bam file which used to call adapter have been removed in the adapter finding results. so what is the filtering step removing these reads?
in addition, what is the difference between polya score and polya length?

**Comment by WeipengMO** [comment]
Hello,

Thank you for your interest in FLEP-seq.

To answer your questions:

- Some reads in bam file may be removed during the adapter finding step because they do not pass the quality filtering criteria. The quality filtering splicing intermediates and reads with low mapping accuracy at the 3′ end. You can find more details about these criterial in this paper (https://www.nature.com/articles/s41477-020-0688-1).
- PolyA length is the estimated length of the poly(A) tail. You can use polyA length for further analysis. PolyA score is for debug only.

I hope this helps.

Best,
Weipeng

**Comment by seven1112233** [comment]
Dear Weipeng,
i see! its helpful! thank you very much!
